### ISSUE TITLE
Repository status

### ISSUE THREAD

**Issue by everyonesdesign** [mitsuhiko/jinja2-tmbundle#13]
@mitsuhiko 
jinja2-tmbundle is the best jinja2 syntax supporting plugin for Sublime Text, I think.
but now pull requests and issues are obviously not reviewed.
I suggest adding someone from PR authors to contributors so they will review and make decisions about further project development.

@leandropls @skotopes @Suor @sorin-ionescu 
I can also suggest an alternative - to use any fork of the project as the main repository and apply all the changes to it. Then upload a new plugin to Sublime Packages repository.

Any thoughts?

**Comment by leandropls** [comment]
I totally agree.

**Comment by everyonesdesign** [comment]
@mitsuhiko  @leandropls @skotopes @Suor @sorin-ionescu 
OK, I moved all the suggested PRs in my repo at https://github.com/kudago/jinja2-tmbundle
Today I'll create new package pull request to package control repo and add a readme.

**Comment by leandropls** [comment]
Thank you @everyonesdesign for taking up this :-)
